# cSpell:disable
FROM node:18-alpine AS build

WORKDIR /app

ARG VITE_API_URL=https://personelpaneli-production.up.railway.app/api
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:18-alpine

WORKDIR /app
RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
